<x-app-layout>
    <div>
        <livewire:page-banner/>
        <livewire:intro-video-text/>
        <livewire:appliances/>
        <livewire:demonstration-classes/>
        <livewire:testimonials/>
    </div>
</x-app-layout>